FROM php:7.4-cli

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN apt-get update && apt-get install -y curl
RUN apt-get install zip unzip
RUN composer require stripe/stripe-php

CMD [ "php", "./index.php" ]
