FROM php:7.2-fpm

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY index.php /var/www/.
COPY composer.json /var/www/.
#COPY docker /var/www/.
WORKDIR /var/www/

USER root

RUN apt-get update && apt-get install -y curl
RUN apt-get install zip unzip
RUN cd /var/www
RUN composer install

# Add user for laravel application
#RUN groupadd -g 1000 www
#RUN useradd -u 1000 -ms /bin/bash -g www www


# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

EXPOSE 9000
CMD ["php-fpm"]
